select * from customer_behaviour_cleaned limit 10;

#1.Total Revenue generated by male vs female
SELECT gender,SUM(purchase_amount) as revenue
FROM customer_behaviour_cleaned
GROUP BY gender;

#2.Which customer used a discount but still spend more than the average purchase amount
SELECT customer_id,purchase_amount FROM customer_behaviour_cleaned
WHERE discount_applied='Yes' AND purchase_amount>=
         (SELECT AVG(purchase_amount) 
         FROM customer_behaviour_cleaned);
         
#3.Which are 5 products with highest avg revenue rating
SELECT item_purchased,ROUND(AVG(review_rating),2) as Average_Product_Rating
FROM customer_behaviour_cleaned
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;

#4.Compare the Avaerage Purchase amount between standard and express shipping
SELECT shipping_type,ROUND(AVG(purchase_amount),2)
FROM customer_behaviour_cleaned
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

#5.Do subscribbed customers spend more ? Compare Average spend and total spend between subscribers and nonsubscribers
SELECT subscription_status,
COUNT(customer_id) as total_customers,
Round(avg(purchase_amount),2 )as avg_spend,
Round(SUM(purchase_amount),2) as total_revenue
FROM customer_behaviour_cleaned
GROUP BY subscription_status
ORDER BY avg_spend DESC;

#6.Which 5 products have the highest percentage of purchase with discount applied
SELECT item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2)
AS discount_rate
FROM customer_behaviour_cleaned
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

/*7.Segment customers into new,returning and loyal based on their total 
number of previous purchases and show count of each segment*/
WITH customer_type as(
         SELECT customer_id,previous_purchases,
         CASE
             WHEN previous_purchases=1 THEN 'new'
             WHEN previous_purchases BETWEEN 2 AND 10 THEN 'returning'
             ELSE 'loyal'
             END AS customer_segment
		FROM customer_behaviour_cleaned
     )
     SELECT customer_segment,count(*) AS 'number_of_customers'
     FROM customer_type
     GROUP BY customer_segment;
     
/*8.What are the top 3 most purchased products from each category*/
WITH item_counts as(
        SELECT category,item_purchased,
        count(customer_id) as total_orders,
        row_number() OVER(partition by category order by count(customer_id)DESC)
        AS item_rank FROM customer_behaviour_cleaned
        GROUP BY category,item_purchased
        )
	SELECT item_rank,category,item_purchased,total_orders
    FROM item_counts
    WHERE item_rank<=3;
    
/*9.Are customers who are repeat buyers(more than 5 previous purchases)also likely to subscribe*/
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer_behaviour_cleaned
WHERE previous_purchases>5
GROUP BY subscription_status;

/*Revenue generated by Age group*/
SELECT age_group,
SUM(purchase_amount) AS total_revenue
FROM customer_behaviour_cleaned
GROUP BY age_group
ORDER BY total_revenue;